name: ci

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: vuejs/vitepress
          ref: main
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          tmp=$(mktemp)
          version=$(jq -r '.version' package.json | cut -d '-' -f 1)-dev.$(git rev-parse --short HEAD)
          jq --arg v "$version" '.version = $v | .name = "@brc-dd/vitepress" | del(.repository)' package.json > "$tmp" && mv "$tmp" package.json
          pnpm i --frozen-lockfile
          pnpm docs-build
          pnpm publish --tag next --ignore-scripts --no-git-checks --access public
